---
#- hosts: localhost
#- hosts: z003zmry-HP-Z8-G4-Workstation, mayuri-VirtualBox
- hosts: all
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/package.yml
    - name: Download XML file
      copy: src=files/example.xml dest=/home/example.xml mode=600
    - name: set ip address in example.xml file 
      xml:
        path: /home/example.xml
        xpath: /note/ipaddress
        value: "{{ansible_default_ipv4.address}}"
    - name: set hostname in example.xml file 
      xml:
        path: /home/example.xml
        xpath: /note/user
        value: "{{inventory_hostname}}"

