---
#- hosts: localhost
#- hosts: z003zmry-HP-Z8-G4-Workstation, mayuri-VirtualBox
- hosts: all
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/package.yml
    - name: Download XML file
      copy: src=files/example.xml dest=/home/mayuri/ansible/example.xml mode=600
    - name: insert ip address in example.xml file 
      lineinfile:
      dest: /home/example.xml
      insertafter: ‘<ipaddress>Jani</ipaddress>'
      line: “{{item}}”
      with_items:
      - “<ipaddress>https://{{ansible_default_ipv4.address}}:9443</ipaddress>"
    - name: insert hostname in example.xml file 
      lineinfile:
      dest: /home/example.xml
      insertafter: ‘<user>Tove</user>'
      line: “{{item}}”
      with_items:
      - “ <user>https://{{inventory_hostname}}:9443</user>"

