---
#- hosts: localhost
#- hosts: z003zmry-HP-Z8-G4-Workstation, mayuri-VirtualBox
- hosts: z003zmry-HP-Z8-G4-Workstation
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/cron.yml
    - include: tasks/package.yml
    - name: Create config file
      action: template src=node/templates/whazzup.in dest=/tmp/whazzup

